# reload config
bind r source-file ~/.tmux.conf

# Force kill --> no y/n
bind x kill-pane
bind & kill-window

# Start window numbering at 1 instead of 0
set -g base-index 1

# Start pane numbering at 1 instead of 0
setw -g pane-base-index 1

# Move the status bar to the top
set -g status-position top

# Optional: Re-number windows automatically when one is closed
set -g renumber-windows on

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection

# Setup 'y' to yank (copy) to system clipboard using pbcopy
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Also let 'Enter' copy to system clipboard
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "pbcopy"
